var targets = {
	"BIC_4graphs.jpg": /.*(BIC_4graphs.jpg)/,
	"course-logo-text.png": /.*(course-logo-text.png)/,
	"cross.png": /.*(cross.png)/,
	"exact.png": /.*(exact.png)/,
	"example_img_in1.jpg": /.*(example_img_in1.jpg)/,
	"example_img_in2.jpg": /.*(example_img_in2.jpg)/,
	"example_sprinkler.png": /.*(example_sprinkler.png)/,
	"final-graphSearch.jpg": /.*(final-graphSearch.jpg)/,
	"final-hillClimbing.jpg": /.*(final-hillClimbing.jpg)/,
	"final-pair.png": /.*(final-pair.png)/,
	"grey_Gibbs_sample1.png": /.*(grey_Gibbs_sample1.png)/,
	"grey_Gibbs_sample2.png": /.*(grey_Gibbs_sample2.png)/,
	"grey_Gibbs_sample3.png": /.*(grey_Gibbs_sample3.png)/,
	"grey_MHGibbs_sample1.png": /.*(grey_MHGibbs_sample1.png)/,
	"grey_MHGibbs_sample2.png": /.*(grey_MHGibbs_sample2.png)/,
	"grey_MHGibbs_sample3.png": /.*(grey_MHGibbs_sample3.png)/,
	"grey_MHSwendsenWang1_sample1.png": /.*(grey_MHSwendsenWang1_sample1.png)/,
	"grey_MHSwendsenWang1_sample2.png": /.*(grey_MHSwendsenWang1_sample2.png)/,
	"grey_MHSwendsenWang1_sample3.png": /.*(grey_MHSwendsenWang1_sample3.png)/,
	"grey_MHSwendsenWang2_sample1.png": /.*(grey_MHSwendsenWang2_sample1.png)/,
	"grey_MHSwendsenWang2_sample2.png": /.*(grey_MHSwendsenWang2_sample2.png)/,
	"grey_MHSwendsenWang2_sample3.png": /.*(grey_MHSwendsenWang2_sample3.png)/,
	"grey_MHUniform_sample1.png": /.*(grey_MHUniform_sample1.png)/,
	"grey_MHUniform_sample2.png": /.*(grey_MHUniform_sample2.png)/,
	"grey_MHUniform_sample3.png": /.*(grey_MHUniform_sample3.png)/,
	"image10.jpg": /.*(image10.jpg)/,
	"image11.jpg": /.*(image11.jpg)/,
	"image12.jpg": /.*(image12.jpg)/,
	"image14.jpg": /.*(image14.jpg)/,
	"image15.jpg": /.*(image15.jpg)/,
	"image16.jpg": /.*(image16.jpg)/,
	"images_review quizzes_fig1.png": /.*(images_review quizzes_fig1.png)/,
	"images_review quizzes_fig2.png": /.*(images_review quizzes_fig2.png)/,
	"images_review quizzes_fig3.png": /.*(images_review quizzes_fig3.png)/,
	"images_review quizzes_fig4.png": /.*(images_review quizzes_fig4.png)/,
	"images_review quizzes_fig5.png": /.*(images_review quizzes_fig5.png)/,
	"images_review quizzes_quiz1-ABCDE model.jpg": /.*(images_review quizzes_quiz1-ABCDE model.jpg)/,
	"images_review quizzes_quiz1-dbn.jpg": /.*(images_review quizzes_quiz1-dbn.jpg)/,
	"images_review quizzes_quiz1-FluNB.png": /.*(images_review quizzes_quiz1-FluNB.png)/,
	"images_review quizzes_quiz1-ground plate.jpg": /.*(images_review quizzes_quiz1-ground plate.jpg)/,
	"images_review quizzes_quiz1-schools plate.jpg": /.*(images_review quizzes_quiz1-schools plate.jpg)/,
	"images_review quizzes_quiz1-TrafficJam.png": /.*(images_review quizzes_quiz1-TrafficJam.png)/,
	"images_review quizzes_quiz2-BN-Imaps.jpg": /.*(images_review quizzes_quiz2-BN-Imaps.jpg)/,
	"images_review quizzes_quiz2-campus_plate2.jpg": /.*(images_review quizzes_quiz2-campus_plate2.jpg)/,
	"images_review quizzes_quiz2-deterministic.jpg": /.*(images_review quizzes_quiz2-deterministic.jpg)/,
	"images_review quizzes_quiz2-Iequiv.jpg": /.*(images_review quizzes_quiz2-Iequiv.jpg)/,
	"images_review quizzes_quiz2-market plate.jpg": /.*(images_review quizzes_quiz2-market plate.jpg)/,
	"images_review quizzes_quiz2-pairwiseMN.jpg": /.*(images_review quizzes_quiz2-pairwiseMN.jpg)/,
	"images_review quizzes_quiz2-Q6-1.jpg": /.*(images_review quizzes_quiz2-Q6-1.jpg)/,
	"images_review quizzes_quiz2-TBNs2.jpg": /.*(images_review quizzes_quiz2-TBNs2.jpg)/,
	"images_review quizzes_quiz2-TBNs.jpg": /.*(images_review quizzes_quiz2-TBNs.jpg)/,
	"images_review quizzes_quiz2-treeCPD.jpg": /.*(images_review quizzes_quiz2-treeCPD.jpg)/,
	"images_review quizzes_quiz2-undirected.jpg": /.*(images_review quizzes_quiz2-undirected.jpg)/,
	"images_review quizzes_VEfactorQuiz.jpg": /.*(images_review quizzes_VEfactorQuiz.jpg)/,
	"images_review quizzes_VE-optionR.jpg": /.*(images_review quizzes_VE-optionR.jpg)/,
	"ismarkov.png": /.*(ismarkov.png)/,
	"like_Gibbs.png": /.*(like_Gibbs.png)/,
	"like_MHGibbs.png": /.*(like_MHGibbs.png)/,
	"like_MHSwendsenWang1.png": /.*(like_MHSwendsenWang1.png)/,
	"like_MHSwendsenWang2.png": /.*(like_MHSwendsenWang2.png)/,
	"like_MHUniform.png": /.*(like_MHUniform.png)/,
	"mcmc_Gibbs.png": /.*(mcmc_Gibbs.png)/,
	"mcmc_MHGibbs.png": /.*(mcmc_MHGibbs.png)/,
	"mcmc_MHSwendsenWang1.png": /.*(mcmc_MHSwendsenWang1.png)/,
	"mcmc_MHSwendsenWang2.png": /.*(mcmc_MHSwendsenWang2.png)/,
	"mcmc_MHUniform.png": /.*(mcmc_MHUniform.png)/,
	"new09_q8b.jpg": /.*(new09_q8b.jpg)/,
	"Q4.jpg": /.*(Q4.jpg)/,
	"quiz2-Q6-1.jpg": /.*(quiz2-Q6-1.jpg)/,
	"quiz4q3a.jpg": /.*(quiz4q3a.jpg)/,
	"SamplingMethodsQ3.jpg": /.*(SamplingMethodsQ3.jpg)/,
	"SamplingMethodsQ4.jpg": /.*(SamplingMethodsQ4.jpg)/,
	"scgnetwork.png": /.*(scgnetwork.png)/,
	"tbn.jpg": /.*(tbn.jpg)/,
	"tick.png": /.*(tick.png)/,
	"top-banner.png": /.*(top-banner.png)/,
	"topbar-coursera-logo.png": /.*(topbar-coursera-logo.png)/,
	"unrolled.png": /.*(unrolled.png)/,
	"ve-ig-g1-o1-1.jpg": /.*(ve-ig-g1-o1-1.jpg)/,
	"ve-ig-g1-o1-2.jpg": /.*(ve-ig-g1-o1-2.jpg)/,
	"ve-ig-g1-o1-3.jpg": /.*(ve-ig-g1-o1-3.jpg)/,
	"ve-ig-g1-o1-4.jpg": /.*(ve-ig-g1-o1-4.jpg)/
}

var imgs = document.getElementsByTagName("img");
for (var img in imgs) {
	if (typeof(imgs[img].src) == "string") {
		for (var key in targets) {
			var reg = targets[key];
			if (imgs[img].src != null) {
				imgs[img].src = chrome.runtime.getURL("images/" + key);
			}
		}
	}
}
